#
# リリースブランチにLuaのソースをねじ込む
#
on:
  push:
    branches:
      - master

jobs:
  fetch_lua_source:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '[Release]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: fetch and add Lua sources, then commit and push to release branch
        run: ./release.sh
