#
# Luaソースを含む完全版をリリースブランチにpushする
#
name: Release preparation

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test swift package
    branches:
      - master
    types:
      - completed

jobs:
  catch_up_with_master:
    name: Apply changes from 'master' to 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Fetch changes and rebase 'release', then merge 'master'
        run: |
          git fetch
          git switch release || git switch -c release
          git rebase master
          git merge master -m "[Merge] catch up with master branch (automated) [no ci]"
          git push origin release

  fetch_lua_source:
    name: Fetch and inject Lua sources
    needs: catch_up_with_master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch 'release'
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Inject Lua sources
        run: |
          ./startup.sh
          rm -rf Sources/LuaSwiftCore/lua/.git

      - name: Add Lua sources and commit forcibly
        run: |
          git add -f Sources/LuaSwiftCore/lua
          git commit -m "[Add] add source files of Lua (automated) [no ci]"
          git push origin release
