#
# Luaソースを含む完全版をリリースブランチにpushし、ドラフトを作成
#
name: Release preparation

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test swift package
    branches:
      - master
    types:
      - completed

jobs:
  fetch_lua_source:
    name: Fetch Lua source files
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if latest commit message contains "[Release]"
        id: check_commit_message
        if: github.event_name != 'workflow_dispatch'
        run: git log -1 --pretty=%B | tr "[A-Z]" "[a-z]" | grep "\[release\]"
        continue-on-error: true

      - name: Git setup
        if: steps.check_commit_message.outcome != 'failure'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Cache lua working directory
        uses: actions/cache@v4
        with:
          path: work
          key: lua-workdir

      - name: fetch and add Lua sources, then commit and push to release branch
        if: steps.check_commit_message.outcome != 'failure'
        run: ./release.sh
