#
# Luaソースを含む完全版をリリースブランチにpushする
#
name: Release preparation

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test swift package
    branches:
      - master
    types:
      - completed

jobs:
  catch_up_with_master:
    name: Apply changes from 'master' to 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Switch branch to 'release', and merge to catch up with 'master'
        run: |
          git fetch
          git switch release || git switch -c release
          git merge --allow-unrelated-histories --no-ff -X theirs -m "[Merge] catch up (automated) [no ci]" master
          git push origin release

  fetch_lua_source:
    name: Fetch and inject Lua sources
    needs: catch_up_with_master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch 'release'
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Inject Lua sources
        run: |
          rm -rf Sources/CygnusCore/lua
          ./startup.sh
          rm -rf Sources/CygnusCore/lua/.git

      - name: Add Lua sources and commit forcibly
        run: |
          git add -f Sources/CygnusCore/lua
          git commit -m "[Add] source files of Lua (automated) [no ci]" || exit 0
          git push origin release

  generate_documentation:
    name: Generate documentation at release branch
    needs: fetch_lua_source
    runs-on: macos-latest

    steps:
      - name: Checkout branch 'release'
        uses: actions/checkout@v4
        with:
          ref: release

      - name: Setup git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Generate and compress documentation
        run: |
          swift package \
            --allow-writing-to-directory docs \
            generate-documentation \
            --disable-indexing \
            --output-path docs \
            --transform-for-static-hosting \
            --hosting-base-path docs \
            --target=Cygnus
          tar czvf docs.tar.gz docs
          rm -rf docs

      - name: Switch to branch 'docs'
        run: |
          git fetch
          git switch docs
          git pull origin docs

      - name: Extract, add, commit, and push documents
        run: |
          tar xzf docs.tar.gz
          rm docs.tar.gz
          git add docs
          if [ ! -e .nojekyll ]; then
            touch .nojekyll
            git add .nojekyll
          fi
          git diff --quiet && git diff --staged --quiet || git commit -m "[Add] documents (automated) [no ci]"
          git push origin docs
