#
# パッケージのソースを準備してテストを行う
#
name: Test swift package

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"

      - name: fetch and add Lua sources
        run: ./startup.sh

      - name: build
        run: swift build

      - name: test
        run: swift test
