#
# パッケージのソースを準備してテストを行う
#
name: Test swift package

on: push

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Lua working directory
        uses: actions/cache@v4
        with:
          path: work
          key: lua-workdir

      - name: Fetch and add Lua sources
        run: ./startup.sh

      - name: Setup Swift 5
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"

      - name: build
        run: swift build

      - name: test
        run: swift test
