#
# パッケージのソースを準備してテストを行う
#
name: Test swift package

on:
  push:
    branches:
      - master
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch and add Lua sources
        run: ./startup.sh

      - name: Setup Swift 5
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5"

      - name: Build and test
        run: swift test
