#
# パッケージのソースを準備してテストを行う
#
name: Simple and lightweight unittest

on:
  push:
    branches:
      - master
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Simple tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch and add Lua sources
        run: ./startup.sh

      - name: Build and test
        run: swift test
